var NDS_PATH="/html/nds";

var gMessageHolder={
	INTERNAL_ERROR:"A server error has occured. More information may be available in the console.",	
	LOADING:"Loading",
	CATEGORY_GUIDE:"Guide",
	TIME_OUT:"Operation timeout",
	DO_YOU_CONFIRM_DELETE:"Do you confirm to delete",
	DO_YOU_CONFIRM_UNSUBMIT:"Do you confirm to revoke submit?",
	DO_YOU_CONFIRM_SUBMIT:"Do you confirm to submit this form?(you can disable this warning in user option window)",
	DO_YOU_CONFIRM_GROUPSUBMIT:"Submit mutiple lines simultanously will trigger special group function, are you sure?",
	MAINTAIN_BY_SYS: "System",
	NO_PERMISSION: "No permission",
	EXCEPTION: "Exception",
	PLEASE_CHECK_SELECTED_LINES:"Please tick lines to select!",
	PLEASE_SELECT_LINES_LESS_THAN:"Please select lines less than 20!",
	MORE_COMMANDS:"Others",
	CONFIRM_DELETE_CHECKED:"Do you confirm to delete checked lines?",
	NO_DATA_TO_PROCESS:"No data to process",
	CAN_NOT_BE_NULL: "Can not be null",
	MUST_BE_DATE_TYPE:"Must be date type",
	MUST_BE_NUMBER_TYPE: "Must be number type",
	PLEASE_SELECT: "Please select",
	MAINTAIN_BY_SYS: "System Maintain",
	NO_PERMISSION: "No permission",
	CMD_ADD:"Add",
	CMD_MODIFY:"Modify",
	CMD_DELETE:"Delete",
	CMD_SUBMIT:"Submit",
	CMD_REFRESH:"Refresh",
	CMD_CXTAB:"Report",
	CMD_LISTADD:"Batch Add",
	CMD_IMPORT:"Import",
	CMD_LISTCOPYTO:"Copy Lines",
	CMD_UPDATE_SELECTION:"Modify Selected",
	CMD_UPDATE_RESULTSET:"Modify ResultSet",
	CMD_PRINT_LIST:"Print List",
	CMD_EXPORT_LIST:"Export List",
	CMD_SMS_LIST:"Send SMS Report",
	CAN_NOT_QUICK_SEARCH:"Exception found. Please reload current page and try again.",
	CONFIRM_DELETE_CHECKED:"Do you confirm to delete checked lines?",
	NO_DATA_TO_PROCESS:"No data to process",
	CONFIRM_DISCARD_CHANGE: "Do you confirm to discard changes",
	DENY_AS_NEW_OBJ:"Forbid as in new object page",
	SET_PRODUCT_ATTRIBUTE:"Set Attribute",
	SHOW_ATTRIBUTE:"Detail",
	LOAD_ATTRIBUTE:"Load",
	ATTRIBUTE_MATRIX_SPLITTED:"Attribute matrix splitted",
	RELOAD_SINCE_ATTRIBUTE_MATRIX_SPLITTED:"Refresh page as some attribute matrix were splitted?",
	NEW_LINE: "New Line",
	EDIT_LINE: "Edit Line",
	INFORMATION: "Information",
	CLOSE_DIALOG:"Close",
	FINISH_TIME:"Finish time",
	IFRAME_TITLE:'Dialog ',
	NO_DATA:"No data",
	INPUT_FIELD:"Please input 0 first",
	CONTAINS:"Contains",
	NOT_ALLOW_TO_POPUP_AS_NOT_MENUOBJ:"Not allow to popup as not menu object",
	CLOSE_DIALOG:"Close",
	EXCLUDE_CHOOSED_ROWS:"Exclude Rows",
	EXCLUDE_ALL:"Exclude All",
	ADD_CHOOSE_ROWS:"Add-Rows",
	ADD_ALL:"Add-All",
	ALREADY_CHOOSED:"Already Choosed",
	ALREADY_EXCLUDE:"Already Exclude",
	SET_ALREADY_CHOOSED:"The set already has been choosed",
	SET_ALREADY_EXCLUDE:"The set already has been excluded",
	CONFIRM_SAVE_FIRST: "Data changed, will save first?",
	AVAILABLE:"(available = Y)",
	CLOSE_AFTER_PRINT:"Click OK button when complete printing.",
	NOT_INTEGER:"The value what you has been input is not integer",
	PRODUCT_NMNER_ZORE:"The number of the product is zore!",
	LINE:"Line",
	TURBO_SCAN:"Turbo Scan",
	SCAN_ERROR:"Error found:x. please enter 0 to close this alert( err count:y)",
	PROCESS_ING:"Please wait until server finishes last request",
	DO_YOU_CONFIRM_UNVOID:"Confirm to unvoid current object?",
	DO_YOU_CONFIRM_VOID:"Confirm to void current object?"

};

