var NDS_PATH="/html/nds";
function PortalInitObject(){}
PortalInitObject.prototype={
};
var gMessageHolder={
	LOADING:"服务器处理中",
	CATEGORY_GUIDE:"分类导航",
	MAINTAIN_BY_SYS: "系统维护",
	TIME_OUT:"操作超时",
	NO_DATA_TO_PROCESS:"没有需要处理的数据",
	DO_YOU_CONFIRM_DELETE:"你确认要执行删除？",
	DO_YOU_CONFIRM_SUBMIT:"你确认要执行提交动作吗?",
	DO_YOU_CONFIRM_GROUPSUBMIT:"当前类型对象的多行同时提交将产生数据“合并”的特殊功能。\\n\\n您确认要执行此特殊功能?\\n\\n（选择“取消”如果您尚不了解所谓“合并”的意义，并查看有关帮助以明确）",
	NO_PERMISSION: "没有权限",
	EXCEPTION: "异常",
	PLEASE_SWITCH_TO_MODIFY_VIEW:"请先切换到修改界面",
	MODIFY_VIEW:"切换到修改界面",
	READ_ONLY_VIEW:"切换到只读界面",
	PLEASE_CHECK_SELECTED_LINES_FOR_SUBMIT:"请在要提交的行首打勾确认！",
	PLEASE_SELECT_LINES_LESS_THAN:"请选择少于20行的数据，以保证客户端响应速度！",
	MORE_COMMANDS:"更多",
	CMD_ADD:"新增",
	CMD_MODIFY:"保存",
	CMD_DELETE:"删除",
	CMD_SUBMIT:"提交",
	CMD_REFRESH:"刷新",
	CMD_CXTAB:"统计",
	CMD_LISTADD:"批量新增",
	CMD_IMPORT:"导入",
	CMD_LISTCOPYTO:"复制",
	CMD_UPDATE_SELECTION:"修改选中行",
	CMD_UPDATE_RESULTSET:"修改结果集",
	CMD_PRINT_LIST:"打印",
	CMD_PRINT_SELECT:"套打",
	CMD_EXPORT_LIST:"导出",
	CMD_SMS_LIST:'短信',
	IFRAME_TITLE:'对话框 ',
	PLS_SELECT_CXTAB:"请在查询栏选择汇总表模板",
	NO_CXTAB:"当前表没有定义汇总表模板",
	CAN_NOT_BE_NULL: "不能为空",
	MUST_BE_DATE_TYPE:"必须是日期型",
	MUST_BE_NUMBER_TYPE: "必须是数字型",
	PLEASE_SELECT: "请选择",
	PLEASE_SETUP_ASSIGNEE:"请设置代办人",
	SEARCH:"查找",
	CONTAINS:"包含",
	NOTCONTAINS:"不包含",
	CLEAR_CONDITION:"点击清除当前条件设置",
	PLEASE_CHECK_SELECTED_LINES:"请在要选择的行首打勾确认！",
	PLEASE_REFRESH_CXTAB_PAGE:"当前操作界面非报表界面布局，请点击报表中心标签页重新进入报表模块后再试",
	NO_DATA:"没有数据",
	CLOSE_DIALOG:"关闭",
	EXCLUDE_CHOOSED_ROWS:"排除选中行",
	EXCLUDE_ALL:"排除全部",
	ADD_CHOOSE_ROWS:"添加选中行",
	ADD_ALL:"添加全部",
	ALREADY_CHOOSED:"已被选择",
	ALREADY_EXCLUDE:"已被排除",
	SET_ALREADY_CHOOSED:"该集合已被选择",
	SET_ALREADY_EXCLUDE:"该集合已被排除",
	NOTICE:"通知",
	PRIORITY:"优先级",
	RELEASETIME:"发送时间",
	SERIALNO:"编号",
	TITLE:"标题",
	URGENT_MESSAGE:"你有$$条紧急消息必需马上处理",
	CONFIRM_MESSAGE:"共有$$条需要确认",
	ALL_NOTICES:"全部通告",
	CMD_VOID:"作废",
	CMD_UNVOID:"取消作废",
	DO_YOU_CONFIRM_VOID:"你确认要作废所选单据吗？",
	DO_YOU_CONFIRM_UNVOID:"你确认要取消作废所选单据吗？"
};
