var NDS_PATH="/html/nds";

var gMessageHolder={
	INTERNAL_ERROR:"服务器处理请求时遇到异常",	
	LOADING:"服务器处理中",
	CATEGORY_GUIDE:"分类导航",
	MAINTAIN_BY_SYS: "系统维护",
	TIME_OUT:"操作超时",
	DO_YOU_CONFIRM_DELETE:"你确认要删除整个0(若有明细也一并删除)？",
	DO_YOU_CONFIRM_UNSUBMIT:"你确认要取消提交吗?",
	DO_YOU_CONFIRM_SUBMIT:"你确认要执行提交动作吗?",
	DO_YOU_CONFIRM_GROUPSUBMIT:"当前类型对象的多行同时提交将产生数据“合并”的特殊功能。\\n\\n您确认要执行此特殊功能?\\n\\n（选择“取消”如果您尚不了解所谓“合并”的意义，并查看有关帮助以明确）",
	NO_PERMISSION: "没有权限",
	EXCEPTION: "异常",
	PLEASE_CHECK_SELECTED_LINES:"请在要选择的行首打勾确认！",
	PLEASE_SELECT_LINES_LESS_THAN:"请选择少于20行的数据，以保证客户端响应速度！",
	MORE_COMMANDS:"更多",
	CONFIRM_DELETE_CHECKED:"你确认要删除选中的行？",
	NO_DATA_TO_PROCESS:"没有需要处理的数据",
	CAN_NOT_BE_NULL: "不能为空",
	MUST_BE_DATE_TYPE:"必须是日期型",
	MUST_BE_NUMBER_TYPE: "必须是数字型",
	PLEASE_SELECT: "请选择",
	MAINTAIN_BY_SYS: "系统维护",
	NO_PERMISSION: "没有足够的权限",
	CMD_ADD:"新增",
	CMD_MODIFY:"修改",
	CMD_DELETE:"删除",
	CMD_SUBMIT:"提交",
	CMD_REFRESH:"刷新",
	CMD_CXTAB:"统计",
	CMD_LISTADD:"批量新增",
	CMD_IMPORT:"导入",
	CMD_LISTCOPYTO:"复制",
	CMD_UPDATE_SELECTION:"修改选中行",
	CMD_UPDATE_RESULTSET:"修改结果集",
	CMD_PRINT_LIST:"打印",
	CMD_PRINT_SELECT:"套打",
	CMD_EXPORT_LIST:"导出",
	CMD_SMS_LIST:"短信",
	CAN_NOT_QUICK_SEARCH:"查询异常，请刷新当前网页后再试",
	CONFIRM_DELETE_CHECKED:"你确认删除选择的行?",
	NO_DATA_TO_PROCESS:"没有数据需要处理",
	CONFIRM_DISCARD_CHANGE: "尚未保存更改，你确认要放弃?",
	DENY_AS_NEW_OBJ:"请先保存，然后执行此操作",
	SET_PRODUCT_ATTRIBUTE:"设置属性",
	SHOW_ATTRIBUTE:"详细",
	LOAD_ATTRIBUTE:"查",
	ATTRIBUTE_MATRIX_SPLITTED:"属性矩阵被拆分为多行保存",
	RELOAD_SINCE_ATTRIBUTE_MATRIX_SPLITTED:"有属性矩阵被拆分成多行，是否刷新页面?",
	NEW_LINE: "新增行",
	EDIT_LINE: "编辑行",
	INFORMATION: "信息",
	CLOSE_DIALOG:"关闭",
	FINISH_TIME:"完成时间",
	IFRAME_TITLE:'对话框 ',
	SEARCH:"查找",
	NO_DATA:"没有数据",
	INPUT_FIELD:"请首先输入0信息",
	CONTAINS:"包含",
		NOTCONTAINS:"不包含",
	NOT_ALLOW_TO_POPUP_AS_NOT_MENUOBJ:"当前明细行禁止弹出窗口显示",
	CLOSE_DIALOG:"关闭",
	EXCLUDE_CHOOSED_ROWS:"排除选中行",
	EXCLUDE_ALL:"排除全部",
	ADD_CHOOSE_ROWS:"添加选中行",
	ADD_ALL:"添加全部",
	ALREADY_CHOOSED:"已被选择",
	ALREADY_EXCLUDE:"已被排除",
	SET_ALREADY_CHOOSED:"该集合已被选择",
	SET_ALREADY_EXCLUDE:"该集合已被排除",
	CONFIRM_SAVE_FIRST: "有数据改动，先保存改动?",
	AVAILABLE:"(可用 = Y)",
	CLOSE_AFTER_PRINT:"请在打印完成后，点击'确定'按钮关闭当前窗口",
	NOT_INTEGER:"您输入的数字不是整数",
	PRODUCT_NMNER_ZORE:"商品的数量为0!",
	LINE:"行",
	TURBO_SCAN:"急速扫描",
	SCAN_ERROR:"扫描条码时发现异常:x。请输入0关闭当前提示(已累计错误y次)",
	PROCESS_ING:"请在服务器处理完成后再输入",
	DO_YOU_CONFIRM_UNVOID:"确认要取消作废当前对象吗？",
	DO_YOU_CONFIRM_VOID:"确认要作废当前对象吗？",
	DO_NOT_PRESS_TWICE:"请勿连续点击!",
	VIEW_ATTACH:"查看附件",
	VIEW_IMAGE:"查看图片",
	PLS_INPUT_URL:"在新增行情况下不能上传文件，请直接输入文件URL或者保存当前行后再上传",
	NEW_ATTACH:"点击此链接或按鼠标右键下载",
	COMPLETE_CLOSE:"操作成功!"
};
