var NDS_PATH="/html/nds";
function PortalInitObject(){}
PortalInitObject.prototype={
};
var gMessageHolder={
	LOADING:"Loading",
	CATEGORY_GUIDE:"Guide",
	TIME_OUT:"Operation timeout",
	NO_DATA_TO_PROCESS:"No data to process",
	DO_YOU_CONFIRM_DELETE:"Do you confirm to delete?",
	DO_YOU_CONFIRM_SUBMIT:"Do you confirm to do submit?(you can disable this warning in user option window)",
	DO_YOU_CONFIRM_GROUPSUBMIT:"Submit mutiple lines simultanously will trigger special group function, are you sure?",
	MAINTAIN_BY_SYS: "System",
	NO_PERMISSION: "No permission",
	EXCEPTION: "Exception",
	PLEASE_SWITCH_TO_MODIFY_VIEW:"Please switch to modify view first",
	MODIFY_VIEW:"Modify View",
	READ_ONLY_VIEW:"Read Only View",
	PLEASE_CHECK_SELECTED_LINES_FOR_SUBMIT:"Please tick lines for submit!",
	PLEASE_SELECT_LINES_LESS_THAN:"Please select lines less than 20!",
	MORE_COMMANDS:"Others",
	CMD_ADD:"Add",
	CMD_MODIFY:"Save",
	CMD_DELETE:"Delete",
	CMD_SUBMIT:"Submit",
	CMD_REFRESH:"Refresh",
	CMD_CXTAB:"Report",
	CMD_LISTADD:"Batch Add",
	CMD_IMPORT:"Import",
	CMD_LISTCOPYTO:"Copy Lines",
	CMD_UPDATE_SELECTION:"Modify Selected",
	CMD_UPDATE_RESULTSET:"Modify ResultSet",
	CMD_PRINT_LIST:"Print List",
	CMD_EXPORT_LIST:"Export List",
	CMD_SMS_LIST:'Send SMS Report',
	IFRAME_TITLE:'Dialog ',
	PLS_SELECT_CXTAB:"Please select crosstab report template in query tab",
	NO_CXTAB:"No crosstab report template defined",
	CAN_NOT_BE_NULL: "Can not be null",
	MUST_BE_DATE_TYPE:"Must be date type",
	MUST_BE_NUMBER_TYPE: "Must be number type",
	PLEASE_SELECT: "Please select",
	PLEASE_SETUP_ASSIGNEE:"Please setup assignee",
	SEARCH: "Search",
	CONTAINS:"Contains",
	NOTCONTAINS:"NOT Contains",
	CLEAR_CONDITION:"Click to clear current filter",
	PLEASE_CHECK_SELECTED_LINES:"Please tick lines to select!",
	PLEASE_REFRESH_CXTAB_PAGE:"Current layout is not for crosstab, please click recport center to enter this layout again",
	NO_DATA:"No data",
	CLOSE_DIALOG:"Close",
	EXCLUDE_CHOOSED_ROWS:"Exclude Rows",
	EXCLUDE_ALL:"Exclude All",
	ADD_CHOOSE_ROWS:"Add-Rows",
	ADD_ALL:"Add-All",
	ALREADY_CHOOSED:"Already Choosed",
	ALREADY_EXCLUDE:"Already Exclude",
	SET_ALREADY_CHOOSED:"The set already has been choosed",
	SET_ALREADY_EXCLUDE:"The set already has been excluded",
	CMD_VOID:"Void",
	CMD_UNVOID:"Unvoid",
	DO_YOU_CONFIRM_VOID:"Do you confirm to void all selection records",
	DO_YOU_CONFIRM_UNVOID:"Do you confirm to unvoid all selection records"
};

