var NDS_PATH="/html/nds";
function PortletInitObject(){}
PortletInitObject.prototype={
};
var gMessageHolder={
	LOADING:"服务器处理中",
	SEARCH:"查找",
	CONTAINS:"包含",
	CLEAR_CONDITION:"点击清除当前条件设置",
	DATA_ERROR:"有数据不合要求，请检查",
	SUM_DATA_ERROR:"汇总值与期望值不一致，请检查拆分",
	INPUT_FIELD:"请首先输入0信息",
	INPUT_FILE_NAME:"请输入文件名",
	TEMPLATE_UPDATED:"您的模板已设置成功！",
	CATEGORY_GUIDE:"分类导航",
	MAINTAIN_BY_SYS: "系统维护",
	TIME_OUT:"操作超时",
	DO_YOU_CONFIRM_DELETE:"你确认要执行删除",
	DO_YOU_CONFIRM_GROUPSUBMIT:"当前类型对象的多行同时提交将产生数据“合并”的特殊功能。\\n\\n您确认要执行此特殊功能?\\n\\n（选择“取消”如果您尚不了解所谓“合并”的意义，并查看有关帮助以明确）",
	NO_PERMISSION: "没有权限",
	EXCEPTION: "异常",
	PLEASE_CHECK_SELECTED_LINES:"请在要选择的行首打勾确认！",
	PLEASE_SELECT_LINES_LESS_THAN:"请选择少于20行的数据，以保证客户端响应速度！",
	MORE_COMMANDS:"更多",
	CONFIRM_DELETE_CHECKED:"你确认要删除选中的行？",
	NO_DATA_TO_PROCESS:"没有需要处理的数据",
	CAN_NOT_BE_NULL: "不能为空",
	MUST_BE_DATE_TYPE:"必须是日期型",
	MUST_BE_NUMBER_TYPE: "必须是数字型",
	PLEASE_SELECT: "请选择",
	MAINTAIN_BY_SYS: "系统维护",
	NO_PERMISSION: "没有足够的权限",
	CMD_ADD:"新增",
	CMD_MODIFY:"修改",
	CMD_DELETE:"删除",
	CMD_SUBMIT:"提交",
	CMD_REFRESH:"刷新",
	CMD_CXTAB:"统计",
	CMD_LISTADD:"批量新增",
	CMD_IMPORT:"导入",
	CMD_LISTCOPYTO:"复制",
	CMD_UPDATE_SELECTION:"修改选中行",
	CMD_UPDATE_RESULTSET:"修改结果集",
	CMD_PRINT_LIST:"打印",
	CMD_EXPORT_LIST:"导出",
	CMD_SMS_LIST:"短信",
	CAN_NOT_QUICK_SEARCH:"查询异常，请刷新当前网页后再试",
	NO_DATA:"没有数据"
};
